apiVersion: v1
kind: Namespace
metadata:
  name: cookeasy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-recipe-deployment
  namespace: cookeasy
  labels:
    app: api-recipe
spec:
  selector:
    matchLabels:
      app: api-recipe
  template:
    metadata:
      labels:
        app: api-recipe
    spec:
      containers:
        - name: api-recipe
          image: haingue/api-recipe:arm64
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-recipe-scale
  namespace: cookeasy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-recipe-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Object
      object:
        metric:
          name: requests-per-second
        describedObject:
          apiVersion: networking.k8s.io/v1beta1
          kind: Ingress
          name: api-recipe-ingress
        target:
          type: Value
          value: 500
---
apiVersion: v1
kind: Service
metadata:
  name: api-recipe-service
  namespace: cookeasy
  labels:
    app: api-recipe
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: api-recipe
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-recipe-ingress
  namespace: cookeasy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api-recipe.haingue.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-recipe-service
                port:
                  number: 8080
